from enum import Enum

class PipelineStage(Enum):
    IDEIA = "IDEIA"
    ESTUDO_TECNICO = "ESTUDO_TECNICO"
    VIABILIDADE_FINANCEIRA = "VIABILIDADE_FINANCEIRA"
    SWOT = "SWOT"
    MERCADO = "MERCADO"
    MARKET_SHARE = "MARKET_SHARE"
    COMITE = "COMITE"
    APROVADO = "APROVADO"
    REPROVADO = "REPROVADO"
    TERMO_ABERTURA = "TERMO_ABERTURA"
    PILOTO = "PILOTO"
    LICOES = "LICOES"
    ESCALA = "ESCALA"
    PAYBACK = "PAYBACK"
    RETORNO = "RETORNO"
    BUSINESS_CASE = "BUSINESS_CASE"
